name: Create PR using GitHub REST API
description: Actiob to create PR from inputs

inputs:
  base-branch:
    description: 'Base branch'
    required: false
  main-branch:
    description: 'Main branch'
    required: false
  pull-request-title:
    description: 'Pull Request Title'
    required: true
  pull-request-body:
    description: 'Pull Request Body'
    required: true
  assignees:
    description: 'Assignees'
    required: true
  labels:
    description: 'Labels (CSV)'
    required: false

runs:
  using: node20
  main: dist/index.js
         

