name: Dynamic Jobs for Each Team

on:
  workflow_dispatch:
    inputs:
      input-teams:
        description: 'Input Teams (CSV)'
        type: string
        required: true

jobs:
  create-dynamic-workflows:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create dynamic matrix
        id: dynamic-matrix
        run: |
          job_count="${{ github.event.inputs.number-of-teams }}"
          matrix_list=""

          for i in $(seq 1 $job_count); do
            matrix_list="${matrix_list} os${i}=ubuntu-latest version${i}=${i} "
          done

          echo "matrix=$matrix_list" >> $GITHUB_OUTPUT
        shell: bash
        
  build:
    needs: create-dynamic-jobs
    

    runs-on: ubuntu-latest

    steps:
      - name: Build and test
        run: |
          echo "Running job version \"**some version**\" on \"**some os**\""
          # Your build and test commands for each job

    

