name: Dynamic Jobs for Each Team

on:
  workflow_dispatch:
    inputs:
      number-of-teams:
        description: 'Number of Teams'
        type: number
        required: true

jobs:
  create-dynamic-jobs:
    runs-on: ubuntu-latest

    outputs:
      matrix_list: ${{ steps.dynamic-matrix.outputs.matrix}}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create dynamic matrix
        id: dynamic-matrix
        run: |
          job_count="${{ github.event.inputs.number-of-teams }}"
          matrix_list=""

          for i in $(seq 1 $job_count); do
            matrix_list="${matrix_list} os${i}=ubuntu-latest version${i}=${i} "
          done

          echo "matrix_list::$matrix_list"
        shell: bash

      - name: Set up matrix
        run: echo "matrix::${{ steps.dynamic-matrix.outputs.matrix }}" >> $GITHUB_OUTPUT
        
  build:
    needs: create-dynamic-jobs
    strategy:
      matrix:
        ${{needs.create-dynamic-jobs.outputs.matrix_list}}

    runs-on: ${{ matrix.os }}

    steps:
      - name: Build and test
        run: |
          echo "Running job version ${{ matrix.version }} on ${{ matrix.os }}"
          # Your build and test commands for each job

    

