name: Dynamic Jobs using Matrix

on:
  workflow_dispatch:
    inputs:
      number_of_jobs:
        description: 'Enter the number of jobs'
        required: true
        type: number

jobs:
  create-dynamic-workflows:
    name: Create Matrix for dynamic jobs
    runs-on: ubuntu-latest
    outputs:
      matrix_list: ${{ steps.dynamic-matrix.outputs.MATRIX }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create dynamic matrix
        id: dynamic-matrix
        run: |
          # Define the upper limit (integer)
          integer="${{ github.event.inputs.number_of_jobs }}"
    
          # Create an array with a sequence of numbers from 1 to the specified integer
          array=($(seq 1 $integer))

          result="["

          for item in "${array[@]}"; do
            result+="$item,"
          done

          # Remove the trailing comma
          result="${result%,}"

          result+="]"

          echo "MATRIX=$result" >> $GITHUB_OUTPUT
        shell: bash

  run-dynamic-jobs:
    name: Run Dynamic Jobs
    runs-on: ubuntu-latest
    strategy:
      matrix: 
        job-number: ${{ needs.create-dynamic-workflows.outputs.MATRIX }}

    steps:
      - name: Run Dynamic Job ${{ matrix.job-number }}
        run: |
          echo "Running job ${{ matrix.job-number }}"
          # Add your job logic here

        
  

    

