name: Fail Pipeline Randomnly 

on:
  workflow_dispatch:
    
jobs:
  call-action:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Call Action for Go/NoGo
      uses: prhsag/alpha/.github/actions/FailPipeline@main
