
name: Create Issue manually

on:
  workflow_dispatch:
    inputs:
      owner:
        description: 'Repository Owner'
        required: true
      repo_name:
        description: 'Repository Name'
        required: true
      title:
        description: 'Issue Title'
        required: true
      body:
        description: 'Issue body'
        required: true
      assignees:
        description: 'Assignees'
        required: true
      labels:
        description: 'Labels (CSV)'
        required: false
        type: string
        

jobs:
  create_issue_manually:
    runs-on: ubuntu-latest
    
    permissions:
      issues: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Create issue using REST API
      id: create-issue
      run: |
        curl --request POST \
        --url https://api.github.com/repos/${{ inputs.owner }}/${{ inputs.repo_name }}/issues \
        --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
        --header 'content-type: application/json' \
        --data '{
           "title": "Manual issue for repository ${{ inputs.owner }}/${{ inputs.repo_name }} \n\n Title: ${{ inputs.title }}",
           "body": "Details: ${{ inputs.body }}. \n\n This issue was manually created by the GitHub Action workflow **${{ github.workflow }}**. \n\n The commit hash was: _${{ github.sha }}_.",
           "assignees":["${{ inputs.assignees }}"],
           "labels":["failed-test-case"]
        }' \
        --fail
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN_PAT }}