
name: Create Issue manually

on:
  workflow_dispatch:
    inputs:
      owner:
        description: 'Repository Owner'
        required: true
        default: prhsag
      repo_name:
        description: 'Repository Name'
        required: true
        default: beta
      title:
        description: 'Issue Title'
        required: true
        default: 'Test Issue from .ts action file'
      body:
        description: 'Issue body'
        required: true
        default: 'This is manually created From prhsag/alpha using .ts file action'
      assignees:
        description: 'Assignees'
        required: true
        default: prhsag
      labels:
        description: 'Labels (CSV)'
        required: false
        type: string
        default: 'failed-test-case'
        

jobs:
  create_issue_manually:
    runs-on: ubuntu-latest
    
    permissions:
      issues: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Create Issue using REST API
      uses: prhsag/alpha/.github/actions/CreateIssue@main
      env:
        TOKEN_PAT: ${{ secrets.TOKEN_PAT }}
      with:
        owner: ${{ inputs.owner }}
        repo_name: ${{ inputs.repo_name }}
        title: ${{ inputs.title }}
        body: ${{ inputs.body }}
        assignees: ${{ inputs.assignees }}
        labels: ${{ inputs.labels }}