name: Pipeline visualization

on:
  workflow_dispatch:


jobs:
  first-job:
    name: First Job
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
  
  second-job:
    needs: first-job
    name: Second Job
    uses: prhsag/alpha/.github/workflows/reusable-workflow-visualization.yaml@main

  third-job:
    needs: first-job
    name: Third Job

    runs-on: ubuntu-latest
    steps:
      - name: Display command
        run: |
          echo "A third job has run"
  final-job:
    needs: [third-job]
    name: Final Job

    runs-on: ubuntu-latest
    steps:
      - name: Display command
        run: |
          echo "The workflow has ended"


