name: Review Step check

on:
    workflow_dispatch:
      inputs:
          proceed:
              description: 'GO/NOGO'
              type: boolean
              required: true
              default: false

jobs:
    get-proceed-status:
        runs-on: ubuntu-latest
        outputs:
            proceed-status: ${{ steps.check-proceed-status.outputs.PROCEED_STATUS }}
    
        steps:
          - name: Checkout code
            uses: actions/checkout@v3
    
          - name: Check Proceed Status
            id: check-proceed-status
            run: |
                if [${{ github.event.inputs.proceed == true }}]
                then
                    echo "Proceed Status: ${{ github.event.inputs.proceed }}"
                else
                    echo "Proceed Status: NOGO"
                    exit 1
                fi
            #   random_number=$((RANDOM % 2))
    
              # Use the random number to determine the output
            #   if [ "$random_number" -eq 0 ]; then
            #     echo "PROCEED_STATUS=GO" >> $GITHUB_OUTPUT
            #   else
            #     echo "PROCEED_STATUS=NOGO" >> $GITHUB_OUTPUT
            #   fi

    await-approval:
        runs-on: ubuntu-latest
        needs: get-proceed-status
        if: ${{ always() && needs.get-proceed-status.result == 'failure'  }}
        environment: QA
        
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Deploy to QA
              run: |
                echo "Deploying to QA, paused for review"        


    deploy-preprod:
        runs-on: ubuntu-latest
        environment: PreProd
        # if: ${{ needs.await-approval.result == 'success' || needs.await-approval.result == 'skipped' }}
        needs:  await-approval

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Deploy to PreProd
              run: |
                echo "Deploying to PreProd"
    
    