name: Review Step check

on:
    workflow_dispatch:
      inputs:
          proceed:
              description: 'GO/NOGO'
              type: boolean
              required: true
              default: false

jobs:
    get-proceed-status:
        runs-on: ubuntu-latest
        outputs:
            proceed-status: ${{ steps.check-proceed-status.outputs.PROCEED_STATUS }}
    
        steps:
          - name: Checkout code
            uses: actions/checkout@v3
    
          - name: Check Proceed Status
            id: check-proceed-status
            run: |
              echo "Proceed Status: ${{ github.event.inputs.proceed }}"
            #   random_number=$((RANDOM % 2))
    
              # Use the random number to determine the output
            #   if [ "$random_number" -eq 0 ]; then
            #     echo "PROCEED_STATUS=GO" >> $GITHUB_OUTPUT
            #   else
            #     echo "PROCEED_STATUS=NOGO" >> $GITHUB_OUTPUT
            #   fi
    deploy-qa:
        runs-on: ubuntu-latest
        environment: QA
        needs: get-proceed-status
        if: ${{ inputs.proceed == false }}
        
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Deploy to QA
              run: |
                echo "Deploying to QA, paused for review"        


    deploy-preprod:
        runs-on: ubuntu-latest
        environment: PreProd
        needs: deploy-qa

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Deploy to PreProd
              run: |
                echo "Deploying to PreProd"
    
    