name: Update Cloned Itrac Ticket Manually

on:
    workflow_dispatch:
        inputs:
          project_url:
            type: string
            required: true
            description: 'Project URL'
            default: 'https://itrac.eur.ad.sag/rest/api/2/issue/AIMT-319'
          input_json:
            type: string
            required: true
            description: 'Input JSON'
            default: '{
              "fields": {
                  "project": {
                      "key": "AIMT"
                  },
                  "issuetype": {
                      "name": "Ticket"
                  }
              },
              "update": {
                  "labels": [
                      {
                          "add": "triaged"
                      },
                      {
                          "remove": "blocker"
                      }
                  ],
                  "summary": [
                      {
                          "set": "Bug in business logic"
                      }
                  ]
                }
              }'
          
          

jobs:
    create-itrac-ticket:
        runs-on: ubuntu-latest

        steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: PUT Request iTrac Ticket from GitHub
          uses: prhsag/update-itrac-action@main
          env:
            API_KEY: ${{ secrets.ITRAC_API_KEY }}

          